import Head from 'next/head'
import Layout from '@/components/layout'
import type { NextPageWithLayout } from './_app'
import { ReactElement } from 'react'

const Page: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Basic example</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </>
  )
}

Page.getLayout = function getLayout (page: ReactElement) {
  return <Layout>{page}</Layout>
}

export default Page
