import Head from 'next/head'
import Nav from '@/components/navItem'

export default function Home () {
  return (
    <>
      <Head>
        <title>Basic example</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div>
          <Nav>Transactions</Nav>
          <Nav>Settings</Nav>
        </div>
      </main>
    </>
  )
}
